# Generated by Django 4.2.25 on 2025-11-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=16)),
                ('original_image_paths', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image_paths', models.JSONField(blank=True, null=True)),
                ('has_multiple_images', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
                ('part_label', models.CharField(blank=True, max_length=32, null=True)),
                ('solution_answer', models.TextField(blank=True, null=True)),
                ('solution_steps', models.JSONField(blank=True, null=True)),
                ('solution_points', models.JSONField(blank=True, null=True)),
                ('solution_verified', models.BooleanField(default=False)),
                ('solution_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='exams_exam_created_66bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order_index'], name='exams_quest_exam_id_9391b0_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='exams_quest_exam_id_50daa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'order_index', 'part_label')},
        ),
    ]
