# Generated by Django 4.2.25 on 2025-11-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial_fixed_schema_v2'),
        ('exams', '0001_initial_fixed_schema_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('summary_short', models.CharField(blank=True, max_length=160)),
                ('raw_llm', models.TextField(blank=True)),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handwriting_summary', models.JSONField(blank=True, null=True)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('llm_confidence_score', models.FloatField(blank=True, null=True)),
                ('phase2_mode', models.BooleanField(default=False, help_text='Whether this result used Phase 2 full-page OCR')),
                ('phase3_mode', models.BooleanField(default=False, help_text='Whether this result used Phase 3 parallel grading')),
                ('full_pages_processed', models.IntegerField(blank=True, help_text='Number of full pages processed', null=True)),
                ('question_lines_extracted', models.IntegerField(blank=True, help_text='Number of OCR lines extracted for this question', null=True)),
                ('critical_errors', models.JSONField(blank=True, help_text='Critical errors that prevented grading', null=True)),
                ('part_errors', models.JSONField(blank=True, help_text='Partial errors found during grading', null=True)),
                ('partial_credit', models.BooleanField(default=False, help_text='Whether partial credit was awarded')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='exams.question')),
                ('submission_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_grading_result', to='submissions.submissionitem')),
            ],
        ),
        migrations.CreateModel(
            name='GradingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=64)),
                ('step_index', models.IntegerField()),
                ('label', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('missing', 'Missing'), ('na', 'Not Applicable'), ('partially_correct', 'Partially Correct')], max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('reason', models.TextField(blank=True)),
                ('annotation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='grading.gradingresult')),
            ],
            options={
                'ordering': ['step_index'],
            },
        ),
        migrations.CreateModel(
            name='OcrPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.IntegerField()),
                ('image_path', models.CharField(max_length=1024)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_summary', models.TextField(blank=True, null=True)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('page_level_issues', models.JSONField(blank=True, null=True)),
                ('critical_ambiguities', models.JSONField(blank=True, null=True)),
                ('auto_rotate_confidence', models.FloatField(blank=True, help_text='Confidence level of auto-rotation detection (0-1)', null=True)),
                ('auto_rotate_degrees', models.IntegerField(blank=True, help_text='Degrees of rotation applied by Mathpix (0, 90, 180, 270)', null=True)),
                ('manual_rotation_applied', models.BooleanField(default=False, help_text='Whether manual rotation was applied due to low auto-rotation confidence')),
                ('manual_rotation_degrees', models.IntegerField(blank=True, help_text='Degrees of manual rotation applied when auto-rotation confidence was low', null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_pages', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='OcrLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('latex', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('gemini_text', models.TextField(blank=True, null=True)),
                ('gemini_latex', models.TextField(blank=True, null=True)),
                ('gemini_confidence', models.FloatField(blank=True, null=True)),
                ('gemini_pro_text', models.TextField(blank=True, null=True)),
                ('gemini_pro_latex', models.TextField(blank=True, null=True)),
                ('gemini_pro_confidence', models.FloatField(blank=True, null=True)),
                ('gemini_pro_ambiguities', models.JSONField(blank=True, null=True)),
                ('refined_by', models.CharField(blank=True, choices=[('flash', 'Gemini Flash'), ('pro', 'Gemini Pro')], max_length=16, null=True)),
                ('changed_from_mathpix', models.BooleanField(default=False)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('handwriting_flag', models.BooleanField(default=False)),
                ('handwriting_notes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='grading.ocrpage')),
            ],
        ),
        migrations.CreateModel(
            name='StepLineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_maps', to='grading.ocrline')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_maps', to='grading.gradingstep')),
            ],
            options={
                'indexes': [models.Index(fields=['step'], name='grading_ste_step_id_1ce593_idx'), models.Index(fields=['line'], name='grading_ste_line_id_633b06_idx')],
                'unique_together': {('step', 'line')},
            },
        ),
        migrations.AddIndex(
            model_name='ocrpage',
            index=models.Index(fields=['submission', 'page_index'], name='grading_ocr_submiss_36e286_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrpage',
            index=models.Index(fields=['sha256'], name='grading_ocr_sha256_78e61a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ocrpage',
            unique_together={('submission', 'page_index')},
        ),
        migrations.AddIndex(
            model_name='ocrline',
            index=models.Index(fields=['page', 'line_index'], name='grading_ocr_page_id_3c19ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrline',
            constraint=models.CheckConstraint(check=models.Q(('x1__gte', 0), ('x2__gt', models.F('x1')), ('y1__gte', 0), ('y2__gt', models.F('y1'))), name='ocr_line_valid_bbox'),
        ),
        migrations.AlterUniqueTogether(
            name='ocrline',
            unique_together={('page', 'line_index')},
        ),
        migrations.AddIndex(
            model_name='gradingstep',
            index=models.Index(fields=['result', 'step_index'], name='grading_gra_result__e63f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingstep',
            index=models.Index(fields=['status'], name='grading_gra_status_0cba4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingstep',
            unique_together={('result', 'step_index')},
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['submission_item'], name='grading_gra_submiss_71ba78_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['question'], name='grading_gra_questio_4864e7_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['needs_human_review'], name='grading_gra_needs_h_9e7ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['is_correct'], name='grading_gra_is_corr_58839b_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['-created_at'], name='grading_gra_created_7ffe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['question', 'is_correct'], name='grading_gra_questio_6887bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradingresult',
            constraint=models.CheckConstraint(check=models.Q(('max_score__gte', 0), ('score__gte', 0), ('score__lte', models.F('max_score'))), name='grading_result_valid_scores'),
        ),
    ]
