# Generated by Django 4.2.25 on 2025-10-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('original_image_paths', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page_indices', models.JSONField(blank=True, null=True)),
                ('answer_image_paths', models.JSONField(blank=True, null=True)),
                ('has_multiple_images', models.BooleanField(default=False)),
                ('answer_bbox', models.JSONField(blank=True, null=True)),
                ('original_image_dimensions', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_items', to='exams.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('error_description', models.TextField(blank=True, null=True)),
                ('error_phrases', models.JSONField(blank=True, null=True)),
                ('critical_errors', models.JSONField(blank=True, null=True)),
                ('part_errors', models.JSONField(blank=True, null=True)),
                ('partial_credit', models.BooleanField(default=False)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('clarify_notes', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='exams.question')),
                ('submission_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='submissions.submissionitem')),
            ],
        ),
    ]
