# Generated by Django 4.2.25 on 2025-11-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial_fixed_schema_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('original_image_paths', models.JSONField(blank=True, null=True)),
                ('triage_report', models.JSONField(blank=True, null=True)),
                ('triage_decision', models.CharField(blank=True, max_length=32, null=True)),
                ('triage_readability_score', models.FloatField(blank=True, null=True)),
                ('triage_confidence', models.FloatField(blank=True, null=True)),
                ('flagged_for_human', models.BooleanField(default=False)),
                ('triage_tier', models.IntegerField(blank=True, choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], null=True)),
                ('triage_score', models.FloatField(blank=True, null=True)),
                ('triage_label', models.CharField(blank=True, max_length=32, null=True)),
                ('recommended_solution', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page_indices', models.JSONField(blank=True, null=True)),
                ('answer_image_paths', models.JSONField(blank=True, null=True)),
                ('has_multiple_images', models.BooleanField(default=False)),
                ('answer_bbox', models.JSONField(blank=True, null=True)),
                ('original_image_dimensions', models.JSONField(blank=True, null=True)),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_items', to='exams.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'question'], name='submissions_submiss_176787_idx'), models.Index(fields=['submission'], name='submissions_submiss_fc3400_idx'), models.Index(fields=['question'], name='submissions_questio_831ca3_idx')],
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['exam', 'created_at'], name='submissions_exam_id_bf4ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['flagged_for_human'], name='submissions_flagged_6ee71e_idx'),
        ),
    ]
