# Generated by Django 4.2.25 on 2025-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionitem',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
